# Generated by Django 2.0.6 on 2018-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема')),
                ('sender', models.EmailField(max_length=254, verbose_name='Відправник')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('copy', models.BooleanField(default=False, help_text='Виберіть для отримання копії запиту на Вашу пошту', verbose_name='Копія')),
            ],
        ),
    ]
