# Generated by Django 2.0.6 on 2018-09-23 18:23

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.installation_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Інсталяція',
                'verbose_name_plural': 'Інсталяції',
            },
        ),
        migrations.CreateModel(
            name='MontageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=services.models.montage_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Montages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Монтаж',
                'verbose_name_plural': 'Монтажі',
            },
        ),
        migrations.CreateModel(
            name='SingleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Інсталяція (детальна)',
                'verbose_name_plural': 'Інсталяції (детальні)',
            },
        ),
        migrations.CreateModel(
            name='SingleMontage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Монтаж (детальний)',
                'verbose_name_plural': 'Монтажі (детальні)',
            },
        ),
        migrations.AddField(
            model_name='montageimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montage_images', to='services.SingleMontage'),
        ),
        migrations.AddField(
            model_name='installationimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalation_images', to='services.SingleInstallation'),
        ),
    ]
