# Generated by Django 2.0.6 on 2018-09-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180930_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_images', to='services.SingleInstallation'),
        ),
    ]
