# Generated by Django 2.0.6 on 2018-09-30 11:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleblog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
