# Generated by Django 2.0.6 on 2018-09-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_singleblog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleblog',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
    ]
