# Generated by Django 2.0.6 on 2018-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=254, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело ')),
            ],
        ),
    ]
