# Generated by Django 2.0.6 on 2018-09-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeview',
            options={'verbose_name': 'Домашня сторінка', 'verbose_name_plural': 'Домашні сторінки'},
        ),
    ]
