# Generated by Django 2.0.6 on 2018-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180916_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='header',
            new_name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті'),
        ),
    ]
