# Generated by Django 2.0.6 on 2018-09-23 16:08

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_image', models.ImageField(upload_to='products/genset/diesel', verbose_name='Фото дизель-генератора')),
                ('diesel_active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Дизель-генератор')),
                ('benzine_image', models.ImageField(upload_to='products/genset/benzine', verbose_name='Фото бензинового генератора')),
                ('benzine_active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Бензиновий генератор')),
                ('gas_image', models.ImageField(upload_to='products/genset/gas', verbose_name='Фото газового генератора')),
                ('gas_active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Газовий генератор')),
                ('welding_image', models.ImageField(upload_to='products/genset/welding', verbose_name='Фото зварювального генератора')),
                ('welding_active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Зварювальний генератор')),
                ('equipment_image', models.ImageField(upload_to='products/genset/equipment', verbose_name='Фото додаткового обладнання')),
                ('equipment_active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Додаткове обладнання')),
            ],
            options={
                'verbose_name': 'Генератори загальна',
                'verbose_name_plural': 'Генератори загальна',
            },
        ),
        migrations.CreateModel(
            name='GensetAdditionalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Додаткове обладнання для генератора',
                'verbose_name_plural': 'Додаткове обладнання для генераторів',
            },
        ),
        migrations.CreateModel(
            name='GensetAdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.genset_additional_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genset_additional_images', to='products.GensetAdditionalEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='GensetBenzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Бензиновий генератор',
                'verbose_name_plural': 'Бензинові генератори',
            },
        ),
        migrations.CreateModel(
            name='GensetBenzineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.genset_benzine_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('benzine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genset_benzine_images', to='products.GensetBenzine')),
            ],
        ),
        migrations.CreateModel(
            name='GensetDiesel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Дизель-генератор',
                'verbose_name_plural': 'Дизель-генератори',
            },
        ),
        migrations.CreateModel(
            name='GensetDieselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.genset_diesel_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('diesel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genset_diesel_images', to='products.GensetDiesel')),
            ],
        ),
        migrations.CreateModel(
            name='GensetGas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Газовий генератор',
                'verbose_name_plural': 'Газові генератори',
            },
        ),
        migrations.CreateModel(
            name='GensetGasImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.genset_gas_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genset_gas_images', to='products.GensetGas')),
            ],
        ),
        migrations.CreateModel(
            name='GensetWelding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Зварювальний генератор',
                'verbose_name_plural': 'Зварювальні генератори',
            },
        ),
        migrations.CreateModel(
            name='GensetWeldingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.genset_welding_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('welding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genset_welding_images', to='products.GensetWelding')),
            ],
        ),
        migrations.CreateModel(
            name='PanelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.panel_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Електрощит',
                'verbose_name_plural': 'Електрощити',
            },
        ),
        migrations.CreateModel(
            name='StabilizerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.stabilizer_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
        ),
        migrations.CreateModel(
            name='Stabilizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Стабілізатор',
                'verbose_name_plural': 'Стабілізатори',
            },
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Джерело безперебійного живлення',
                'verbose_name_plural': 'Джерела безперебійного живлення',
            },
        ),
        migrations.CreateModel(
            name='UpsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.ups_upload_location)),
                ('active', models.BooleanField(default=True, help_text='Для відображення на сайті необхідно виділити!', verbose_name='Відображати на сайті')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups_images', to='products.Ups')),
            ],
        ),
        migrations.AddField(
            model_name='stabilizerimage',
            name='stabilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stabilizer_images', to='products.Stabilizers'),
        ),
        migrations.AddField(
            model_name='panelimage',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_images', to='products.Panels'),
        ),
    ]
